using System;
using System.Collections.Generic;
using System.Text;

namespace Raven.Identity
{
    /// <summary>
    /// The type of ID to create for users.
    /// </summary>
    public enum UserIdType
    {
        /// <summary>
        /// The ID will utilize the user's email, e.g. "AppUsers/johndoe@mail.com"
        /// </summary>
        Email,
        /// <summary>
        /// The ID will utilize the user's username, e.g. "AppUsers/johndoe"
        /// </summary>
        UserName,
        /// <summary>
        /// The ID will be generated by the server dynamically, e.g. "AppUsers/1-A"
        /// </summary>
        ServerGenerated
    }
}
